// 1. Find the 5 most recent orders
`SELECT * FROM orders ORDER BY order_date DESC LIMIT 5`;

// 2. Find the total number of customers
`SELECT COUNT(*) AS total_customers FROM customers`;

// 3. Count how many products are in each category
`SELECT category_id, COUNT(*) AS product_count 
    FROM products GROUP BY category_id`;

// 4. Find the average order value
`SELECT AVG(total_amount) AS average_order_value FROM orders`;

// 5. List all products with a price greater than $50
`SELECT * FROM products WHERE price > 50`;

// 6. Find the average salary per department
`SELECT department_id, AVG(salary) AS average_salary 
    FROM employees GROUP BY department_id`;

// 7. Find the users who signed up in the last 30 days
`SELECT * FROM users WHERE signup_date >= NOW() - INTERVAL 30 DAY`;

// 8. Find the top 3 products with the highest sales
`SELECT product_id, SUM(quantity) AS total_sales 
    FROM order_items 
    GROUP BY product_id 
    ORDER BY total_sales DESC 
    LIMIT 3`;

// OR    
`SELECT product_name, SUM(sales_amount) AS total_sales
    FROM sales
    GROUP BY product_name
    ORDER BY total_sales DESC
    LIMIT 3;`

// 9. Find the total revenue generated in the last month
`SELECT SUM(total_amount) AS total_revenue 
    FROM orders WHERE order_date >= DATE_SUB(CURDATE(), INTERVAL 1 MONTH)`;

// 10. Find the top 5 customers by total spending
`SELECT customer_id, SUM(total_amount) AS total_spending 
    FROM orders GROUP BY customer_id 
    ORDER BY total_spending DESC 
    LIMIT 5`;

// 11. Find the products that have never been ordered
`SELECT * FROM products 
    WHERE product_id NOT IN (SELECT DISTINCT product_id FROM order_items)`;

// 12. Find the average order value for each customer
`SELECT customer_id, AVG(total_amount) AS average_order_value 
    FROM orders GROUP BY customer_id`;

// 13. Find products that are out of stock
`SELECT * FROM products WHERE stock_quantity = 0`;

// 14. Count how many orders are in each status (e.g., pending, shipped, delivered)
`SELECT status, COUNT(*) AS order_count 
    FROM orders GROUP BY status`;

// 15. Find the top 5 products with the highest ratings
`SELECT product_id, AVG(rating) AS average_rating 
    FROM product_reviews 
    GROUP BY product_id 
    ORDER BY average_rating DESC 
    LIMIT 5`;

// 16. Find the total number of orders placed by each customer
`SELECT customer_id, COUNT(*) AS total_orders 
    FROM orders GROUP BY customer_id`;

// 17. Find the total number of products sold in each category
`SELECT p.category_id, SUM(oi.quantity) AS total_products_sold 
    FROM order_items oi 
    JOIN products p ON oi.product_id = p.product_id 
    GROUP BY p.category_id`;

// 18. Find customers who never placed an order
`SELECT * FROM customers 
    WHERE customer_id NOT IN (SELECT DISTINCT customer_id FROM orders)`;

// 19. Find the total revenue generated by each product
`SELECT p.product_id, SUM(oi.quantity * p.price) AS total_revenue 
    FROM order_items oi 
    JOIN products p ON oi.product_id = p.product_id 
    GROUP BY p.product_id`;

// 20. Find the top 5 customers with the highest average order value
`SELECT customer_id, AVG(total_amount) AS average_order_value 
    FROM orders GROUP BY customer_id 
    ORDER BY average_order_value DESC 
    LIMIT 5`;

// 21. Find the total number of products in stock for each category
`SELECT category_id, SUM(stock_quantity) AS total_products_in_stock 
    FROM products GROUP BY category_id`;

// 22. Find highest paid employees in each department
`SELECT department_id, employee_id, salary 
    FROM employees e1 
    WHERE salary = (SELECT MAX(salary) 
    FROM employees e2 
    WHERE e2.department_id = e1.department_id)`;

// 23. Find duplicate email addresses and how many times they appear
`SELECT email, COUNT(*) AS email_count 
    FROM users GROUP BY email HAVING email_count > 1`;

// 24. List every employee along with their manager's name
`SELECT e.employee_id, e.first_name, e.last_name, m.first_name AS manager_first_name, m.last_name AS manager_last_name 
    FROM employees e 
    LEFT JOIN employees m ON e.manager_id = m.employee_id`;

// 25. Find the second highest order amount, safely handling ties
`SELECT DISTINCT total_amount 
    FROM orders 
    ORDER BY total_amount DESC 
    LIMIT 1 OFFSET 1`;

// 26. Find the total number of orders placed in each month of the current year
`SELECT MONTH(order_date) AS order_month, COUNT(*) AS total_orders 
    FROM orders 
    WHERE YEAR(order_date) = YEAR(CURDATE()) 
    GROUP BY order_month`;

// 27. Find the average rating for each product
`SELECT product_id, AVG(rating) AS average_rating 
    FROM product_reviews 
    GROUP BY product_id`;

// 28. Find the top 5 products with the highest sales in the last month
`SELECT product_id, SUM(quantity) AS total_sales 
    FROM order_items
    WHERE order_id IN (SELECT order_id FROM orders WHERE order_date >= DATE_SUB(CURDATE(), INTERVAL 1 MONTH))
    GROUP BY product_id 
    ORDER BY total_sales DESC 
    LIMIT 5`;

// 29. Find the total number of customers who have placed at least one order
`SELECT COUNT(DISTINCT customer_id) AS total_customers_with_orders 
    FROM orders`;

// 30. Find the total revenue generated by each category
`SELECT p.category_id, SUM(oi.quantity * p.price) AS total_revenue 
    FROM order_items oi 
    JOIN products p ON oi.product_id = p.product_id 
    GROUP BY p.category_id`;